### ISSUE TITLE
Gather relevant documentations about the metrics in Overview, Benchmarking and Trends

### ISSUE THREAD

**Issue by saeedip** [saeedip/MetricMate#8]

**Comment by chhabrat** [comment]
I would like to work on this task.

**Comment by chhabrat** [comment]
1) Metric guidance - https://assets.ctfassets.net/o78em1y1w4i4/54o8UH5cdisCqfUFpSG03T/b1c80b9c4a9fcf168f85065a0f044a64/ELSV-13013-Elsevier-Research-Metrics-Book-r12-WEB.pdf

2) Cite score metrics - https://www.elsevier.com/products/scopus/metrics/citescore

3) We can use some points form this link for ppt - https://www.elsevier.com/products/scival
